/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NewRouteImport } from './routes/new'
import { Route as AdminBrandingRouteImport } from './routes/admin/branding'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminGroupsRouteImport } from './routes/admin/groups'
import { Route as AdminHealthRouteImport } from './routes/admin/health'
import { Route as AdminPresetsRouteImport } from './routes/admin/presets'
import { Route as AdminRetentionRouteImport } from './routes/admin/retention'
import { Route as AdminServersRouteImport } from './routes/admin/servers'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as ApiBackendSplatRouteImport } from './routes/api/backend/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/admin/branding',
  path: '/admin/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/admin/groups',
  path: '/admin/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/admin/health',
  path: '/admin/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPresetsRoute = AdminPresetsRouteImport.update({
  id: '/admin/presets',
  path: '/admin/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRetentionRoute = AdminRetentionRouteImport.update({
  id: '/admin/retention',
  path: '/admin/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServersRoute = AdminServersRouteImport.update({
  id: '/admin/servers',
  path: '/admin/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackendSplatRoute = ApiBackendSplatRouteImport.update({
  id: '/api/backend/$',
  path: '/api/backend/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/presets': typeof AdminPresetsRoute
  '/admin/retention': typeof AdminRetentionRoute
  '/admin/servers': typeof AdminServersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/presets': typeof AdminPresetsRoute
  '/admin/retention': typeof AdminRetentionRoute
  '/admin/servers': typeof AdminServersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/clientes': typeof ClientesIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/presets': typeof AdminPresetsRoute
  '/admin/retention': typeof AdminRetentionRoute
  '/admin/servers': typeof AdminServersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/new'
    | '/admin/branding'
    | '/admin/companies'
    | '/admin/groups'
    | '/admin/health'
    | '/admin/presets'
    | '/admin/retention'
    | '/admin/servers'
    | '/admin/users'
    | '/api/health'
    | '/clientes/$id'
    | '/requests/$id'
    | '/clientes/'
    | '/requests/'
    | '/api/backend/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/new'
    | '/admin/branding'
    | '/admin/companies'
    | '/admin/groups'
    | '/admin/health'
    | '/admin/presets'
    | '/admin/retention'
    | '/admin/servers'
    | '/admin/users'
    | '/api/health'
    | '/clientes/$id'
    | '/requests/$id'
    | '/clientes'
    | '/requests'
    | '/api/backend/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/new'
    | '/admin/branding'
    | '/admin/companies'
    | '/admin/groups'
    | '/admin/health'
    | '/admin/presets'
    | '/admin/retention'
    | '/admin/servers'
    | '/admin/users'
    | '/api/health'
    | '/clientes/$id'
    | '/requests/$id'
    | '/clientes/'
    | '/requests/'
    | '/api/backend/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  NewRoute: typeof NewRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminPresetsRoute: typeof AdminPresetsRoute
  AdminRetentionRoute: typeof AdminRetentionRoute
  AdminServersRoute: typeof AdminServersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ClientesIdRoute: typeof ClientesIdRoute
  RequestsIdRoute: typeof RequestsIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  ApiBackendSplatRoute: typeof ApiBackendSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/admin/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/admin/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/presets': {
      id: '/admin/presets'
      path: '/admin/presets'
      fullPath: '/admin/presets'
      preLoaderRoute: typeof AdminPresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/retention': {
      id: '/admin/retention'
      path: '/admin/retention'
      fullPath: '/admin/retention'
      preLoaderRoute: typeof AdminRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/servers': {
      id: '/admin/servers'
      path: '/admin/servers'
      fullPath: '/admin/servers'
      preLoaderRoute: typeof AdminServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backend/$': {
      id: '/api/backend/$'
      path: '/api/backend/$'
      fullPath: '/api/backend/$'
      preLoaderRoute: typeof ApiBackendSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  NewRoute: NewRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminPresetsRoute: AdminPresetsRoute,
  AdminRetentionRoute: AdminRetentionRoute,
  AdminServersRoute: AdminServersRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiHealthRoute: ApiHealthRoute,
  ClientesIdRoute: ClientesIdRoute,
  RequestsIdRoute: RequestsIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  ApiBackendSplatRoute: ApiBackendSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
