import assert from 'node:assert/strict';
import { spawn, type ChildProcess } from 'node:child_process';
import { once } from 'node:events';
import { createServer } from 'node:net';
import { createRequire } from 'node:module';
import { access } from 'node:fs/promises';
import { join } from 'node:path';

const requireApi = createRequire(new URL('../apps/api/package.json', import.meta.url)); const pg = requireApi('pg'); const bcrypt = requireApi('bcryptjs'); const { EncryptionService } = requireApi('@rdgen/domain'); process.loadEnvFile('.env');
async function command(program: string, args: string[]): Promise<void> { const child = spawn(program, args, { stdio: 'inherit', env: process.env }); const [code] = await once(child, 'exit') as [number | null]; if (code !== 0) throw new Error(`${program} ${args.join(' ')} failed`); }
async function availablePort(): Promise<number> { const server = createServer(); server.listen(0, '127.0.0.1'); await once(server, 'listening'); const address = server.address(); assert(address && typeof address !== 'string'); await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); return address.port; }
async function waitForApi(baseUrl: string): Promise<void> { const deadline = Date.now() + 30_000; while (Date.now() < deadline) { try { if ((await fetch(`${baseUrl}/health`)).ok) return; } catch { /* starting */ } await new Promise((resolve) => setTimeout(resolve, 200)); } throw new Error('API did not start'); }
function cookie(response: Response): string { const match = (response.headers.get('set-cookie') ?? '').match(/rdgen_session=([^;]*)/); assert(match, 'login did not set a session cookie'); return `rdgen_session=${match[1]}`; }
async function json(url: string, init: RequestInit = {}) { const response = await fetch(url, init); return { response, body: await response.json().catch(() => ({})) as Record<string, unknown> }; }
async function stop(child: ChildProcess): Promise<void> { if (child.exitCode !== null) return; child.kill('SIGTERM'); await Promise.race([once(child, 'exit'), new Promise((resolve) => setTimeout(resolve, 5_000))]); if (child.exitCode === null) child.kill('SIGKILL'); }

const permissions = { keyboard: true, clipboard: true, fileTransfer: true, audio: true, tunnel: false, remoteRestart: true, recording: false, blockInput: true, remoteConfigModification: false, printer: true, camera: false, terminal: true };
function preset(direction: string, installationEnabled: boolean) { return { direction, installationEnabled, settingsEnabled: installationEnabled, approvalMode: 'password', denyLanDiscovery: true, enableDirectIp: true, autoDisconnect: false, hideConnectionManager: true, removeWallpaper: true, offlineMode: false, suppressNewVersionNotification: true, permissions }; }
function png(): string { return 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGP4z8DwHwAFAAH/iZk9HQAAAABJRU5ErkJggg=='; }
const headers = (cookie: string, csrf: string) => ({ cookie, 'x-csrf-token': csrf, 'content-type': 'application/json' });

async function main(): Promise<void> {
  await command('docker', ['compose', 'up', '-d', 'postgres', 'redis']); await command(process.execPath, ['--import', 'tsx', 'apps/api/src/database/migrate.ts']);
  const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL }); const suffix = `${Date.now()}-${Math.random().toString(16).slice(2)}`; const password = 'SmokeRequestPassword123'; const secret = 'SMOKE-SERVER-SECRET-NOT-RETURNED';
  const admin = await pool.query<{ id: string }>(`INSERT INTO users (email, password_hash, role, status) VALUES ($1, $2, 'administrator', 'active') RETURNING id`, [`request-admin-${suffix}@example.invalid`, await bcrypt.hash(password, 12)]);
  const port = await availablePort(); const baseUrl = `http://127.0.0.1:${port}`; const api = spawn(join(process.cwd(), 'node_modules', '.bin', 'tsx'), ['src/main.ts'], { cwd: join(process.cwd(), 'apps', 'api'), env: { ...process.env, API_PORT: String(port), API_BASE_URL: baseUrl }, stdio: ['ignore', 'pipe', 'pipe'] }); api.stdout.on('data', (data) => process.stdout.write(`[api] ${data}`)); api.stderr.on('data', (data) => process.stderr.write(`[api] ${data}`));
  let userId: string | undefined; let requestId: string | undefined; let noBrandingRequestId: string | undefined; let serverId: string | undefined; let brandingId: string | undefined; let spareBrandingId: string | undefined; let protectedIds: string[] = []; let presetIds: string[] = [];
  try {
    await waitForApi(baseUrl); const login = await json(`${baseUrl}/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email: `request-admin-${suffix}@example.invalid`, password }) }); assert.equal(login.response.status, 201); const adminCookie = cookie(login.response); const adminCsrf = login.body.csrfToken as string;
    const user = await json(`${baseUrl}/admin/users`, { method: 'POST', headers: headers(adminCookie, adminCsrf), body: JSON.stringify({ email: `request-user-${suffix}@example.invalid`, password, role: 'user' }) }); assert.equal(user.response.status, 201); userId = (user.body.user as { id: string }).id;
    const branding = await json(`${baseUrl}/admin/brandings`, { method: 'POST', headers: headers(adminCookie, adminCsrf), body: JSON.stringify({ name: `brand-${suffix}`, companyName: 'Smoke Company', androidApplicationId: 'org.example.smoke', theme: 'dark', themeScope: 'default', icon: { contentType: 'image/png', dataBase64: png() }, logo: { contentType: 'image/png', dataBase64: png() }, privacyScreen: { contentType: 'image/png', dataBase64: png() } }) }); assert.equal(branding.response.status, 201); brandingId = (branding.body.branding as { id: string }).id;
    const spare = await json(`${baseUrl}/admin/brandings`, { method: 'POST', headers: headers(adminCookie, adminCsrf), body: JSON.stringify({ name: `spare-${suffix}`, companyName: 'Spare Company', theme: 'system', themeScope: 'override', icon: { contentType: 'image/png', dataBase64: png() }, logo: { contentType: 'image/png', dataBase64: png() }, privacyScreen: { contentType: 'image/png', dataBase64: png() } }) }); assert.equal(spare.response.status, 201); spareBrandingId = (spare.body.branding as { id: string }).id;
    const spareImages = (await pool.query<{ icon: string; logo: string; privacy: string }>('SELECT icon_storage_key AS icon, logo_storage_key AS logo, privacy_storage_key AS privacy FROM brandings WHERE id = $1', [spareBrandingId])).rows[0];
    const server = await json(`${baseUrl}/admin/rustdesk-servers`, { method: 'POST', headers: headers(adminCookie, adminCsrf), body: JSON.stringify({ name: `smoke-${suffix}`, configuration: { host: 'relay.example.invalid', port: '21116', publicKey: secret, apiServer: 'https://api.example.invalid' } }) }); assert.equal(server.response.status, 201); serverId = (server.body.server as { id: string }).id;
    const full = await json(`${baseUrl}/admin/presets`, { method: 'POST', headers: headers(adminCookie, adminCsrf), body: JSON.stringify({ name: `full-${suffix}`, profile: 'full', configuration: preset('incoming', true) }) }); assert.equal(full.response.status, 201); presetIds.push((full.body.preset as { id: string }).id);
    const qs = await json(`${baseUrl}/admin/presets`, { method: 'POST', headers: headers(adminCookie, adminCsrf), body: JSON.stringify({ name: `qs-${suffix}`, profile: 'qs', configuration: preset('incoming', false) }) }); assert.equal(qs.response.status, 201); presetIds.push((qs.body.preset as { id: string }).id);
    const userLogin = await json(`${baseUrl}/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email: `request-user-${suffix}@example.invalid`, password }) }); assert.equal(userLogin.response.status, 201); const userCookie = cookie(userLogin.response); const userCsrf = userLogin.body.csrfToken as string;
    const requestBody = { displayName: 'Smoke Support', technicalName: `smoke-support-${suffix}`, serverId, brandingId, presets: { full: (full.body.preset as { id: string }).id, qs: (qs.body.preset as { id: string }).id }, profiles: ['full', 'qs'], platforms: ['windows', 'linux', 'android'], version: '1.4.9', profilePasswords: { full: 'SMOKE-FULL-PASSWORD', qs: 'SMOKE-QS-PASSWORD' }, images: { icon: { contentType: 'image/png', dataBase64: png() } } };
    const requestHeaders = { ...headers(userCookie, userCsrf), 'idempotency-key': `smoke-${suffix}` }; const created = await json(`${baseUrl}/build-requests`, { method: 'POST', headers: requestHeaders, body: JSON.stringify(requestBody) }); assert.equal(created.response.status, 201); requestId = (created.body.request as { id: string }).id; assert.equal((created.body.jobs as unknown[]).length, 6);
    const replay = await json(`${baseUrl}/build-requests`, { method: 'POST', headers: requestHeaders, body: JSON.stringify(requestBody) }); assert.equal(replay.response.status, 201); assert.deepEqual(replay.body, created.body);
    const noBrandingBody = { displayName: 'Unbranded Smoke Support', technicalName: `unbranded-smoke-${suffix}`, serverId, presets: { full: (full.body.preset as { id: string }).id }, profiles: ['full'], platforms: ['windows', 'linux'], version: '1.4.9' };
    const noBranding = await json(`${baseUrl}/build-requests`, { method: 'POST', headers: { ...headers(userCookie, userCsrf), 'idempotency-key': `unbranded-smoke-${suffix}` }, body: JSON.stringify(noBrandingBody) }); assert.equal(noBranding.response.status, 201); noBrandingRequestId = (noBranding.body.request as { id: string }).id; assert.equal((noBranding.body.jobs as unknown[]).length, 2);
    const noBrandingSnapshots = await pool.query<{ id: string }>(`SELECT p.id FROM protected_records p JOIN build_jobs j ON j.resolved_configuration_protected_id = p.id WHERE j.request_id = $1`, [noBrandingRequestId]); assert.equal(noBrandingSnapshots.rowCount, 2); protectedIds.push(...noBrandingSnapshots.rows.map((row) => row.id));
    const blocked = await json(`${baseUrl}/admin/brandings/${brandingId}`, { method: 'DELETE', headers: headers(adminCookie, adminCsrf) }); assert([400, 409].includes(blocked.response.status));
    const requestImages = (await pool.query<{ icon: string; logo: string | null; privacy: string | null }>('SELECT icon_storage_key AS icon, logo_storage_key AS logo, privacy_storage_key AS privacy FROM build_requests WHERE id = $1', [requestId])).rows[0]; const brandingImages = (await pool.query<{ icon: string; logo: string; privacy: string }>('SELECT icon_storage_key AS icon, logo_storage_key AS logo, privacy_storage_key AS privacy FROM brandings WHERE id = $1', [brandingId])).rows[0]; assert.notEqual(requestImages.icon, brandingImages.icon); assert.equal(requestImages.logo, null); assert.equal(requestImages.privacy, null);
    const snapshots = await pool.query<{ id: string; ciphertext: string; integrity: string; keyId: string }>(`SELECT p.id, p.ciphertext, p.integrity, p.key_id AS "keyId" FROM protected_records p JOIN build_jobs j ON j.resolved_configuration_protected_id = p.id WHERE j.request_id = $1`, [requestId]); assert.equal(snapshots.rowCount, 6); protectedIds = snapshots.rows.map((row) => row.id); const encryption = new EncryptionService(Buffer.from(process.env.APP_ENCRYPTION_KEY!, 'base64'), process.env.APP_ENCRYPTION_KEY_ID!); for (const snapshot of snapshots.rows) { const resolved = JSON.parse(encryption.decrypt(snapshot).toString('utf8')); assert.equal(resolved.iconStorageKey, requestImages.icon); assert.equal(resolved.logoStorageKey, brandingImages.logo); assert.equal(resolved.privacyStorageKey, brandingImages.privacy); }
    const spareDelete = await json(`${baseUrl}/admin/brandings/${spareBrandingId}`, { method: 'DELETE', headers: headers(adminCookie, adminCsrf) }); assert.equal(spareDelete.response.status, 200); for (const key of Object.values(spareImages)) await assert.rejects(access(join(process.env.APP_STORAGE_PATH!, key))); spareBrandingId = undefined;
    console.log('Request smoke passed: branding images and cleanup, free 3-platform shared-version matrix, split profile passwords, inherited/overridden image resolution, unbranded request creation, referenced-branding protection, encrypted snapshots, and idempotent replay.');
  } finally {
    await stop(api); if (requestId) await pool.query('DELETE FROM build_requests WHERE id = $1', [requestId]).catch(() => undefined); if (noBrandingRequestId) await pool.query('DELETE FROM build_requests WHERE id = $1', [noBrandingRequestId]).catch(() => undefined); if (protectedIds.length) await pool.query('DELETE FROM protected_records WHERE id = ANY($1::uuid[])', [protectedIds]).catch(() => undefined);
    if (brandingId) await pool.query('DELETE FROM brandings WHERE id = $1', [brandingId]).catch(() => undefined); if (spareBrandingId) await pool.query('DELETE FROM brandings WHERE id = $1', [spareBrandingId]).catch(() => undefined);
    if (serverId) { const record = await pool.query<{ id: string }>('SELECT configuration_protected_id AS id FROM rustdesk_servers WHERE id = $1', [serverId]).catch(() => ({ rows: [] })); await pool.query('DELETE FROM rustdesk_servers WHERE id = $1', [serverId]).catch(() => undefined); if (record.rows[0]) await pool.query('DELETE FROM protected_records WHERE id = $1', [record.rows[0].id]).catch(() => undefined); }
    if (presetIds.length) await pool.query('DELETE FROM presets WHERE id = ANY($1::uuid[])', [presetIds]).catch(() => undefined); await pool.query('DELETE FROM audit_events WHERE actor_id = $1 OR actor_id = $2', [admin.rows[0].id, userId ?? '']).catch(() => undefined); await pool.query('DELETE FROM users WHERE id = $1 OR id = $2', [admin.rows[0].id, userId ?? '']).catch(() => undefined); await pool.end();
  }
}
void main().catch((error) => { console.error(`Request smoke failed: ${error instanceof Error ? error.message : 'unknown error'}`); process.exitCode = 1; });
