import { Link, useParams } from '@tanstack/react-router';
import { ArrowLeft, ArrowUpRight, ChevronDown, Download, ExternalLink, RotateCcw, ShieldAlert, XCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { useData, type UiJob as Job } from '@/lib/api-provider';
import { platformLabel } from '@/lib/types';
import { confirmSwal } from '@/lib/swal';
import { Empty, Page, SectionHeading, Status, Tag, prettyDate, profileName } from './shared';

export function RequestDetail() {
  const { id } = useParams({ from: '/requests/$id' });
  const { data, currentUser, repository } = useData();
  const request = data.requests.find((r) => r.id === id);
  const [busy, setBusy] = useState(false);
  if (!request || !(currentUser?.role === 'administrator' || request.canManage === true || request.visibility === 'published')) return <Page><Empty title="Solicitação não encontrada" description="Esta solicitação não está disponível para sua conta." action={<Button asChild variant="outline"><Link to="/dashboard">Voltar</Link></Button>} /></Page>;
  const own = currentUser?.role === 'administrator' || request.canManage === true;
  const jobs = data.jobs.filter((j) => j.requestId === id);
  const selected = request;
  async function toggle() { setBusy(true); try { await repository.visibility(id, selected.visibility === 'private' ? 'published' : 'private'); toast.success(selected.visibility === 'private' ? 'Solicitação publicada' : 'Solicitação ocultada'); } finally { setBusy(false); } }
  return <Page><div className="breadcrumb"><Link to="/dashboard">DASHBOARD</Link><span>/</span> {request.displayName.toUpperCase()}</div><div className="detail-back"><Link to="/dashboard"><ArrowLeft size={15} /> Voltar às solicitações</Link></div><SectionHeading eyebrow={`SOLICITAÇÃO / ${request.id.toUpperCase()}`} title={request.displayName} description={`${request.technicalName} · criada por ${data.users.find((u) => u.id === request.creatorId)?.email ?? 'usuário'} · ${prettyDate(request.createdAt)}`} action={own ? <Button variant="outline" disabled={busy} onClick={toggle}>{request.visibility === 'private' ? 'Publicar solicitação' : 'Ocultar solicitação'}</Button> : undefined} /><div className="detail-summary"><div><small>VISIBILIDADE</small><strong><span className={`visibility-dot ${request.visibility}`} />{request.visibility === 'private' ? 'Privada' : 'Publicada'}</strong></div><div><small>SERVIDOR</small><strong>{data.servers.find((s) => s.id === request.serverId)?.name || 'Indisponível'}</strong></div><div><small>PERFIS</small><strong>{request.profiles?.map(profileName).join(' + ') || '—'}</strong></div><div><small>JOBS CRIADOS</small><strong>{jobs.length.toString().padStart(2, '0')}</strong></div></div><div className="section-title"><div><h2>Jobs desta solicitação</h2><span>Um build independente por perfil e plataforma</span></div></div><div className="jobs-list">{jobs.map((job) => <JobPanel key={job.id} job={job} own={Boolean(own)} />)}</div></Page>;
}

function JobPanel({ job, own }: { job: Job; own: boolean }) {
  const { repository } = useData();
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [links, setLinks] = useState<{ statusUrl?: string; actionUrl?: string }>({});
  const retry = ['falhou', 'aguardando_retry', 'início_indeterminado', 'concluído_parcial'].includes(job.status);
  const cancel = ['rascunho', 'enfileirado', 'iniciando', 'aguardando_rdgen'].includes(job.status);
  useEffect(() => { if (own) void repository.externalLinks(job.id).then(setLinks).catch(() => undefined); }, [own, job.id, repository]);
  async function action(type: 'reconcile' | 'retry' | 'cancel') { const messages = { reconcile: 'Reconciliar este build com o serviço externo?', retry: 'Reenviar este job? Se o início anterior não foi confirmado, isso pode duplicar um build externo.', cancel: 'Cancelar este job?' }; if (!(await confirmSwal(messages[type]))) return; setBusy(true); try { await repository.jobAction(job.id, type, type === 'reconcile' ? { uuid: job.id, filename: `artifact-${job.id}`, platform: job.platform } : type === 'retry' ? { riskConfirmed: true } : undefined); toast.success(type === 'reconcile' ? 'Reconciliação registrada' : type === 'retry' ? 'Nova tentativa enfileirada' : 'Job cancelado'); } finally { setBusy(false); } }
  async function external(url: string) { if (await confirmSwal('Abrir link externo?', { text: 'Este link abre uma página externa que pode ser pública.', confirmText: 'Abrir' })) window.open(url, '_blank', 'noopener,noreferrer'); }
  return <article className="job-panel"><div className="job-top"><div className="job-title"><div className="job-icon">{job.profile === 'full' ? 'F' : 'Q'}</div><div><div className="job-title-line"><h3>{profileName(job.profile)} <span>/</span> {platformLabel[job.platform]}</h3><Tag>v{job.version}</Tag></div><small>{job.id.toUpperCase()} · Criado {prettyDate(job.createdAt)}</small></div></div><Status status={job.status} /></div><div className="job-body"><div className="progress-info"><small>PROGRESSO DO RDGEN</small><p>{job.progress}</p></div><div className="job-meta"><div><small>TENTATIVA ATUAL</small><strong>#{job.attempts.at(-1)?.number || 1}</strong></div><div><small>ATUALIZADO</small><strong>{prettyDate(job.updatedAt)}</strong></div></div></div>{job.status === 'início_indeterminado' && <div className="warning-strip"><ShieldAlert size={17} /> O início do build não foi confirmado. Reconcilie antes de tentar novamente para evitar duplicação externa.</div>}{job.artifacts.length > 0 && <div className="artifacts"><div className="mini-heading">ARTEFATOS DISPONÍVEIS {job.status === 'concluído_parcial' && <span>· resultado parcial</span>}</div>{job.artifacts.map((artifact) => <div className="artifact" key={artifact.id}><div><Download size={16} /><strong>{artifact.fileName}</strong><small>{(artifact.sizeBytes / 1048576).toFixed(1)} MB · SHA-256 {artifact.sha256.slice(0, 12)}…</small></div><Button variant="outline" size="sm" asChild><a href={repository.downloadUrl(artifact.id)}><Download /> Baixar</a></Button></div>)}</div>}
    <div className="job-footer"><Button variant="ghost" size="sm" onClick={() => setOpen(!open)} aria-expanded={open}><ChevronDown size={15} className={open ? 'rotate-180' : ''} /> Histórico de tentativas ({job.attempts.length})</Button><div className="job-actions">{own && links.statusUrl && <Button variant="ghost" size="sm" onClick={() => external(links.statusUrl!)} title="Link externo potencialmente público"><ExternalLink /> Status RDGen <span className="external-label">externo</span></Button>}{own && links.actionUrl && <Button variant="ghost" size="sm" onClick={() => external(links.actionUrl!)} title="Link externo potencialmente público"><ArrowUpRight /> Actions <span className="external-label">externo</span></Button>}{own && job.status === 'início_indeterminado' && <Button variant="outline" size="sm" disabled={busy} onClick={() => void action('reconcile')}><RotateCcw /> Reconciliar</Button>}{own && retry && <Button variant="outline" size="sm" disabled={busy} onClick={() => void action('retry')}><RotateCcw /> Retry manual</Button>}{own && cancel && <Button variant="ghost" size="sm" disabled={busy} onClick={() => void action('cancel')}><XCircle /> Cancelar</Button>}</div></div>{open && <div className="attempts">{[...job.attempts].reverse().map((attempt) => <div className="attempt" key={attempt.id}><div className="attempt-marker" /><strong>Tentativa #{attempt.number}</strong><Status status={attempt.status} /><span>{attempt.stage || attempt.errorCode || '—'}</span><small>{prettyDate(attempt.createdAt)} · atualizado {prettyDate(attempt.updatedAt)}</small></div>)}</div>}</article>;
}
