import { Link, useNavigate } from '@tanstack/react-router';
import { motion } from 'motion/react';
import { Activity, ArrowLeft, ArrowUpRight, Boxes, ChevronRight, CircleHelp, Database, HardDrive, KeyRound, LayoutDashboard, List, LogOut, Menu, Plus, Server, Settings2, Shield, Users, X, type LucideIcon } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { useData } from '@/lib/api-provider';
import { toast } from 'sonner';
import { statusLabel, type JobStatus } from '@/lib/types';
import { formatDistanceToNow } from 'date-fns';
import { ptBR } from 'date-fns/locale';

export const prettyDate = (date:string) => formatDistanceToNow(new Date(date),{addSuffix:true,locale:ptBR});
export const profileName = (p:string) => p==='full'?'Full':'QuickSupport';
const statusTone:Record<JobStatus,string>={rascunho:'neutral',enfileirado:'info',iniciando:'info',início_indeterminado:'warning',aguardando_rdgen:'info',aguardando_retry:'warning',baixando:'info',validando:'info',concluído:'success',concluído_parcial:'warning',falhou:'danger',cancelado:'neutral'};
export function Status({status}:{status:JobStatus}) { return <span className={`status status-${statusTone[status]}`}><span className="status-dot"/>{statusLabel[status]}</span>; }
export function Tag({children}:{children:ReactNode}) {return <span className="tag">{children}</span>}
export function Dialog({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><Button variant="ghost" size="icon" onClick={onClose} aria-label="Fechar"><X/></Button></div>{children}</div></div>}
function ChangePassword({onClose}:{onClose:()=>void}){const {repository}=useData();const [currentPassword,setCurrentPassword]=useState('');const [newPassword,setNewPassword]=useState('');const [confirm,setConfirm]=useState('');const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(newPassword!==confirm){toast.error('As senhas não coincidem.');return}setBusy(true);try{await repository.changePassword(currentPassword,newPassword);toast.success('Senha alterada.');onClose();}catch(cause){toast.error(cause instanceof Error?cause.message:'Não foi possível alterar a senha.');}finally{setBusy(false);}}return <Dialog title="Alterar senha" onClose={onClose}><form className="form-stack" onSubmit={submit}><label>Senha atual<input type="password" required value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label>Nova senha<input type="password" required minLength={12} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><small>Mínimo 12 caracteres, com maiúscula, minúscula e número.</small></label><label>Confirmar nova senha<input type="password" required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><div className="modal-actions"><Button variant="outline" type="button" onClick={onClose}>Cancelar</Button><Button type="submit" disabled={busy}>Salvar senha</Button></div></form></Dialog>}
export function SectionHeading({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}) { return <div className="page-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action&&<div className="heading-action">{action}</div>}</div> }
const nav: {label:string;to:string;icon:LucideIcon;admin?:boolean}[]=[{label:'Dashboard',to:'/dashboard',icon:LayoutDashboard},{label:'Todas as solicitações',to:'/requests',icon:List},{label:'Nova solicitação',to:'/new',icon:Plus},{label:'Usuários',to:'/admin/users',icon:Users,admin:true},{label:'Servidores RustDesk',to:'/admin/servers',icon:Server,admin:true},{label:'Presets',to:'/admin/presets',icon:Settings2,admin:true},{label:'Branding',to:'/admin/branding',icon:Boxes,admin:true},{label:'Retenção e armazenamento',to:'/admin/retention',icon:HardDrive,admin:true},{label:'Saúde do sistema',to:'/admin/health',icon:Activity,admin:true}];
export function AppShell({children}:{children:ReactNode}) {const {currentUser,logout}=useData();const navigate=useNavigate();const [menu,setMenu]=useState(false);const [changingPassword,setChangingPassword]=useState(false);if(!currentUser) return <div className="login-wrap"><Login/></div>;const admin=currentUser.role==='administrator';return <div className="app-shell"><aside className={`sidebar ${menu?'sidebar-open':''}`}><div className="brand"><div className="brand-mark"><span/></div><div><strong>RDGen<span className="brand-light"> Automator</span></strong><small>BUILD CONTROL / 01</small></div><Button variant="ghost" size="icon" className="mobile-close" onClick={()=>setMenu(false)} aria-label="Fechar menu"><X/></Button></div><div className="nav-caption">WORKSPACE</div><nav>{nav.filter(item=>!item.admin).map(item=><NavItem key={item.to} item={item} close={()=>setMenu(false)}/>)}</nav>{admin&&<><div className="nav-caption nav-caption-admin">ADMINISTRAÇÃO</div><nav>{nav.filter(item=>item.admin).map(item=><NavItem key={item.to} item={item} close={()=>setMenu(false)}/>)}</nav></>}<div className="sidebar-bottom"><div className="environment"><span className="live-dot"/> Ambiente conectado <CircleHelp size={13}/></div><div className="user-box"><div className="avatar">{currentUser.email.slice(0,1).toUpperCase()}</div><div className="user-details"><strong>{currentUser.email}</strong><small>{admin?'Administrador':'Usuário comum'}</small></div><Button variant="ghost" size="icon" title="Alterar senha" aria-label="Alterar senha" onClick={()=>setChangingPassword(true)}><KeyRound size={17}/></Button><Button variant="ghost" size="icon" title="Sair" aria-label="Sair" onClick={()=>void logout().finally(()=>navigate({to:'/'}))}><LogOut size={17}/></Button></div></div></aside>{changingPassword&&<ChangePassword onClose={()=>setChangingPassword(false)}/>}{menu&&<div className="mobile-backdrop" onClick={()=>setMenu(false)}/>}<main className="main-area"><div className="mobile-bar"><Button variant="ghost" size="icon" onClick={()=>setMenu(true)} aria-label="Abrir menu"><Menu/></Button><strong>RDGen Automator</strong></div><motion.div key={typeof location==='undefined'?'page':location.pathname} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.22}} className="content">{children}</motion.div></main></div>}
function NavItem({item,close}:{item:(typeof nav)[number];close:()=>void}) {const Icon=item.icon;return <Link to={item.to} onClick={close} className="nav-link" activeProps={{className:'nav-link active'}}><Icon size={17} strokeWidth={1.8}/><span>{item.label}</span><ChevronRight size={14} className="nav-chevron"/></Link>}
function Login(){const {login}=useData();const navigate=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await login(email,password);navigate({to:'/dashboard'});}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível entrar.');}finally{setBusy(false);}}return <div className="login-content"><div className="login-logo"><div className="brand-mark"><span/></div> RDGen<span> Automator</span></div><div className="login-panel"><div className="eyebrow">ACESSO AO WORKSPACE</div><h1>Bem-vindo de volta.</h1><p>Entre para acompanhar suas solicitações de build.</p><form onSubmit={submit} className="form-stack"><label>E-mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@empresa.com"/></label><label>Senha<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Sua senha"/></label>{error&&<div role="alert" className="field-error">{error}</div>}<Button disabled={busy} size="lg" type="submit" className="w-full">{busy?'Entrando...':'Entrar no painel'} <ArrowUpRight size={16}/></Button></form></div><div className="login-foot"><span className="live-dot"/> Ambiente conectado</div></div>}
export function Restricted({children}:{children:ReactNode}) {const {currentUser}=useData();if(!currentUser)return <AppShell>{null}</AppShell>;if(currentUser.role!=='administrator')return <AppShell><SectionHeading title="Acesso não disponível" description="Esta área pertence à administração."/><Button asChild variant="outline"><Link to="/dashboard"><ArrowLeft/> Voltar ao dashboard</Link></Button></AppShell>;return <AppShell>{children}</AppShell>}
export function Page({children}:{children:ReactNode}) {return <AppShell>{children}</AppShell>}
export function SkeletonRows(){return <div className="skeleton-list">{[1,2,3,4].map(i=><div key={i} className="skeleton-row"/>)}</div>}
export function Empty({title,description,action}:{title:string;description:string;action?:ReactNode}) {return <div className="empty-state"><Database size={32}/><h3>{title}</h3><p>{description}</p>{action}</div>}
