import { createContext, useContext, type ReactNode } from 'react';
import { useQueries, useQuery, useQueryClient } from '@tanstack/react-query';
import { backend } from './api';
import { dataUrlToImage, type Branding, type BrandingImages, type BuildRequest, type Job, type Preset, type Profile, type Server, type User } from './types';

type UiServer = { id: string; name: string; host: string; port: string; publicKey: string; apiServer: string; linkUrl: string; downloadUrl: string };
type UiConfig = { direction: string; install: boolean; settings: boolean; approval: string; lan: boolean; directIp: boolean; autoDisconnect: boolean; hideConnectionManager: boolean; wallpaper: boolean; offline: boolean; suppressUpdates: boolean; permissions: Preset['configuration']['permissions'] };
type UiPreset = { id: string; name: string; profile: Profile; version: number; config: UiConfig };
type UiBranding = { id: string; name: string; company: string; androidId: string; theme: string; themeScope: string; images: Partial<Record<'icon' | 'logo' | 'privacy', string>> };
export type UiJob = Job & { requestId: string; startedAt: string; progress: string; artifacts: Array<{ id: string; fileName: string; sizeBytes: number; sha256: string }>; statusUrl?: string; actionsUrl?: string };
type UiRequest = BuildRequest & { creatorId?: string; profiles: Profile[] };
function uiServer(server: Server): UiServer { const c = server.configuration ?? { host: '', publicKey: '' }; return { id: server.id, name: server.name, host: c.host, port: String(c.port ?? ''), publicKey: c.publicKey, apiServer: c.apiServer ?? '', linkUrl: c.linkUrl ?? '', downloadUrl: c.downloadUrl ?? '' }; }
function optionServer(server: { id: string; name: string }): UiServer { return { id: server.id, name: server.name, host: '', port: '', publicKey: '', apiServer: '', linkUrl: '', downloadUrl: '' }; }
function realServer(server: UiServer): Server { return { id: server.id.startsWith('new-') ? '' : server.id, name: server.name, configuration: { host: server.host, ...(server.port ? { port: server.port } : {}), publicKey: server.publicKey, ...(server.apiServer ? { apiServer: server.apiServer } : {}), ...(server.linkUrl ? { linkUrl: server.linkUrl } : {}), ...(server.downloadUrl ? { downloadUrl: server.downloadUrl } : {}) } }; }
function uiConfig(configuration: Preset['configuration']): UiConfig { return { direction: configuration.direction === 'incoming' ? 'Entrada' : configuration.direction === 'outgoing' ? 'Saída' : 'Ambas', install: configuration.installationEnabled, settings: configuration.settingsEnabled, approval: configuration.approvalMode === 'password' ? 'Senha permanente' : configuration.approvalMode === 'click' ? 'Clique para aprovar' : 'Ambos', lan: !configuration.denyLanDiscovery, directIp: configuration.enableDirectIp, autoDisconnect: configuration.autoDisconnect, hideConnectionManager: configuration.hideConnectionManager, wallpaper: configuration.removeWallpaper, offline: configuration.offlineMode, suppressUpdates: configuration.suppressNewVersionNotification, permissions: configuration.permissions }; }
function realPreset(preset: UiPreset): Preset { const c = preset.config; return { id: preset.id.startsWith('new-') ? '' : preset.id, name: preset.name, profile: preset.profile, version: preset.version, configuration: { direction: c.direction === 'Entrada' ? 'incoming' : c.direction === 'Saída' ? 'outgoing' : 'both', installationEnabled: c.install, settingsEnabled: c.settings, approvalMode: c.approval === 'Senha permanente' ? 'password' : c.approval === 'Clique para aprovar' ? 'click' : 'password-click', denyLanDiscovery: !c.lan, enableDirectIp: c.directIp, autoDisconnect: c.autoDisconnect, hideConnectionManager: c.hideConnectionManager, removeWallpaper: c.wallpaper, offlineMode: c.offline, suppressNewVersionNotification: c.suppressUpdates, permissions: c.permissions } }; }
function uiPreset(preset: Preset): UiPreset { return { id: preset.id, name: preset.name, profile: preset.profile, version: preset.version, config: uiConfig(preset.configuration) }; }
function optionPreset(preset: { id: string; name: string; profile: Profile; version: number }): UiPreset { return { id: preset.id, name: preset.name, profile: preset.profile, version: preset.version, config: { direction: 'Ambas', install: preset.profile === 'full', settings: true, approval: 'Senha permanente', lan: false, directIp: false, autoDisconnect: false, hideConnectionManager: false, wallpaper: false, offline: false, suppressUpdates: false, permissions: Object.fromEntries(['keyboard', 'clipboard', 'fileTransfer', 'audio', 'tunnel', 'remoteRestart', 'recording', 'blockInput', 'remoteConfigModification', 'printer', 'camera', 'terminal'].map((key) => [key, true])) as Record<string, boolean> } }; }
function uiBranding(branding: Branding): UiBranding { const image = (slot: 'icon' | 'logo' | 'privacy') => `/api/backend/admin/brandings/${branding.id}/images/${slot}`; return { id: branding.id, name: branding.name, company: branding.companyName, androidId: branding.androidApplicationId ?? '', theme: branding.theme === 'dark' ? 'Escuro' : branding.theme === 'light' ? 'Claro' : 'Sistema', themeScope: branding.themeScope === 'override' ? 'Cliente' : 'Sistema', images: { icon: image('icon'), logo: image('logo'), privacy: image('privacy') } }; }
function optionBranding(branding: { id: string; name: string; companyName: string; theme: 'light' | 'dark' | 'system' }): UiBranding { const image = (slot: 'icon' | 'logo' | 'privacy') => `/api/backend/admin/brandings/${branding.id}/images/${slot}`; return { id: branding.id, name: branding.name, company: branding.companyName, androidId: '', theme: branding.theme === 'dark' ? 'Escuro' : branding.theme === 'light' ? 'Claro' : 'Sistema', themeScope: 'Sistema', images: { icon: image('icon'), logo: image('logo'), privacy: image('privacy') } }; }
function realBranding(branding: UiBranding): { branding: Branding; images: BrandingImages } { const theme = branding.theme === 'Escuro' ? 'dark' : branding.theme === 'Claro' ? 'light' : 'system'; const images: BrandingImages = {}; const icon = dataUrlToImage(branding.images.icon); const logo = dataUrlToImage(branding.images.logo); const privacyScreen = dataUrlToImage(branding.images.privacy); if (icon) images.icon = icon; if (logo) images.logo = logo; if (privacyScreen) images.privacyScreen = privacyScreen; return { branding: { id: branding.id.startsWith('new-') ? '' : branding.id, name: branding.name, companyName: branding.company, ...(branding.androidId ? { androidApplicationId: branding.androidId } : {}), theme, themeScope: branding.themeScope === 'Cliente' ? 'override' : 'default' }, images }; }
function uiJob(job: Job, requestId: string, artifacts: Array<{ id: string; sha256: string; bytes: number }>): UiJob { return { ...job, requestId, startedAt: job.createdAt, progress: job.lastErrorCode ?? job.attempts[0]?.stage ?? 'Aguardando atualização do RDGen.', artifacts: artifacts.map((artifact) => ({ id: artifact.id, fileName: `artifact-${artifact.id}`, sizeBytes: Number(artifact.bytes), sha256: artifact.sha256 })) }; }

type Data = { users: User[]; servers: UiServer[]; presets: UiPreset[]; brandings: UiBranding[]; requests: UiRequest[]; jobs: UiJob[]; releases: string[]; releasesCheckedAt: string; retention: { artifacts: number; logos: number }; health: Record<string, 'ok' | 'degraded'>; checkedAt: string };
type Repository = { saveUser(input: { email: string; password: string; role: 'administrator' | 'user' } | User): Promise<void>; disableUser(id: string): Promise<void>; saveServer(server: UiServer): Promise<void>; deleteServer(id: string): Promise<void>; savePreset(preset: UiPreset): Promise<void>; deletePreset(id: string): Promise<void>; saveBranding(branding: UiBranding): Promise<void>; deleteBranding(id: string): Promise<void>; saveRetention(artifacts: number, logos: number): Promise<void>; refreshHealth(): Promise<void>; refreshReleases(): Promise<void>; createRequest(input: { displayName: string; technicalName: string; serverId: string; profiles: Profile[]; platforms: string[]; version: string; brandingId?: string | undefined; images: Partial<Record<'icon' | 'logo' | 'privacy', string>>; presetIds: Partial<Record<Profile, string>>; password?: string | undefined; profilePasswords?: Partial<Record<Profile, string | undefined>> | undefined; idempotencyKey: string }): Promise<string>; visibility(id: string, visibility: 'private' | 'published'): Promise<void>; jobAction(id: string, action: 'cancel' | 'retry' | 'reconcile', body?: unknown): Promise<void>; externalLinks(id: string): Promise<{ statusUrl?: string; actionUrl?: string }>; downloadUrl(id: string): string };
const DataContext = createContext<{ data: Data; currentUser: User | null; loading: boolean; repository: Repository; login(email: string, password: string): Promise<User>; logout(): Promise<void> } | null>(null);
const empty: Data = { users: [], servers: [], presets: [], brandings: [], requests: [], jobs: [], releases: [], releasesCheckedAt: new Date(0).toISOString(), retention: { artifacts: 30, logos: 30 }, health: {}, checkedAt: new Date(0).toISOString() };
export function ApiProvider({ children }: { children: ReactNode }) {
  const client = useQueryClient();
  const me = useQuery({ queryKey: ['me'], queryFn: backend.me, retry: false, staleTime: Infinity }); const currentUser = me.data?.user ?? null;
  const requests = useQuery({ queryKey: ['requests'], queryFn: backend.requests, enabled: !!currentUser }); const options = useQuery({ queryKey: ['options'], queryFn: backend.options, enabled: !!currentUser });
  const admin = currentUser?.role === 'administrator'; const users = useQuery({ queryKey: ['users'], queryFn: backend.users, enabled: admin }); const servers = useQuery({ queryKey: ['servers'], queryFn: backend.servers, enabled: admin }); const presets = useQuery({ queryKey: ['presets'], queryFn: backend.presets, enabled: admin }); const brandings = useQuery({ queryKey: ['brandings'], queryFn: backend.brandings, enabled: admin }); const settings = useQuery({ queryKey: ['settings'], queryFn: backend.settings, enabled: admin }); const health = useQuery({ queryKey: ['health'], queryFn: backend.health, enabled: admin });
  const details = useQueries({ queries: (requests.data?.requests ?? []).map((request) => ({ queryKey: ['request', request.id], queryFn: () => backend.request(request.id), enabled: !!currentUser })) });
  const complete = details.map((query) => query.data).filter(Boolean) as Array<{ request: BuildRequest; jobs: Job[]; artifacts: Array<{ id: string; sha256: string; bytes: number }> }>;
  const data: Data = currentUser ? { users: users.data?.users ?? [], servers: (servers.data?.servers ?? []).length ? (servers.data?.servers ?? []).map(uiServer) : (options.data?.servers ?? []).map(optionServer), presets: (presets.data?.presets ?? []).length ? (presets.data?.presets ?? []).map(uiPreset) : (options.data?.presets ?? []).map(optionPreset), brandings: (brandings.data?.brandings ?? []).length ? (brandings.data?.brandings ?? []).map(uiBranding) : (options.data?.brandings ?? []).map(optionBranding), requests: (requests.data?.requests ?? []).map((request) => { const detail = complete.find((candidate) => candidate.request.id === request.id); return { ...request, ...detail?.request, profiles: detail?.jobs.map((job) => job.profile).filter((profile, index, all) => all.indexOf(profile) === index) ?? [] }; }), jobs: complete.flatMap((detail) => detail.jobs.map((job) => uiJob(job, detail.request.id, detail.artifacts))), releases: options.data?.releases ?? [], releasesCheckedAt: new Date().toISOString(), retention: { artifacts: settings.data?.settings.artifactRetentionDays ?? 30, logos: settings.data?.settings.logoRetentionDays ?? 30 }, health: Object.fromEntries(Object.entries(health.data?.dependencies ?? {}).map(([key, value]) => [key === 'postgres' ? 'database' : key === 'redis' ? 'queue' : key, value.ready ? 'ok' : 'degraded'])), checkedAt: new Date().toISOString() } : empty;
  const invalidate = () => client.invalidateQueries();
  const repository: Repository = { saveUser: async (input) => { if ('status' in input && input.status === 'disabled') { await backend.disableUser(input.id); } else { await backend.createUser(input); } await invalidate(); }, disableUser: async (id) => { await backend.disableUser(id); await invalidate(); }, saveServer: async (server) => { await backend.saveServer(realServer(server)); await invalidate(); }, deleteServer: async (id) => { await backend.deleteServer(id); await invalidate(); }, savePreset: async (preset) => { await backend.savePreset(realPreset(preset)); await invalidate(); }, deletePreset: async (id) => { await backend.deletePreset(id); await invalidate(); }, saveBranding: async (branding) => { const converted = realBranding(branding); await backend.saveBranding(converted.branding, converted.images); await invalidate(); }, deleteBranding: async (id) => { await backend.deleteBranding(id); await invalidate(); }, saveRetention: async (artifacts, logos) => { await backend.saveSettings(artifacts, logos); await invalidate(); }, refreshHealth: async () => { await client.refetchQueries({ queryKey: ['health'] }); }, refreshReleases: async () => { await backend.refreshReleases(); await invalidate(); }, createRequest: async (input) => { const response = await backend.createRequest({ displayName: input.displayName, technicalName: input.technicalName, serverId: input.serverId, brandingId: input.brandingId, presets: input.presetIds, profiles: input.profiles, platforms: input.platforms, version: input.version, permanentPassword: input.password || undefined, profilePasswords: input.profilePasswords, images: { icon: dataUrlToImage(input.images.icon), logo: dataUrlToImage(input.images.logo), privacyScreen: dataUrlToImage(input.images.privacy) } }, input.idempotencyKey); await invalidate(); return response.request.id; }, visibility: async (id, visibility) => { await backend.visibility(id, visibility); await invalidate(); }, jobAction: async (id, action, body) => { await backend.job(id, action, body); await invalidate(); }, externalLinks: async (id) => (await backend.externalLinks(id)).links, downloadUrl: (id) => `/api/backend/artifacts/${id}/download` };
  async function login(email: string, password: string) { const result = await backend.login(email, password); client.setQueryData(['me'], { user: result.user }); return result.user; }
  async function logout() { await backend.logout(); client.setQueryData(['me'], undefined); client.removeQueries(); }
  return <DataContext.Provider value={{ data, currentUser, loading: me.isLoading || requests.isLoading || options.isLoading, repository, login, logout }}>{children}</DataContext.Provider>;
}
export function useData() { const value = useContext(DataContext); if (!value) throw new Error('ApiProvider is required'); return value; }
export type { UiBranding as Branding, UiPreset as Preset, UiServer as Server };
export const defaultConfig = (profile: Profile) => ({ direction: 'Ambas', install: profile === 'full', settings: true, approval: 'Ambos', lan: false, directIp: false, autoDisconnect: false, hideConnectionManager: false, wallpaper: false, offline: false, suppressUpdates: false, permissions: Object.fromEntries(['keyboard', 'clipboard', 'fileTransfer', 'audio', 'tunnel', 'remoteRestart', 'recording', 'blockInput', 'remoteConfigModification', 'printer', 'camera', 'terminal'].map((key) => [key, true])) as Record<string, boolean> });
